name: npcx
main: net.gamerservices.npcx.npcx
version: 0.465t
author: mixxit, tickleman
website: http://www.gamerservices.net
description: >
    NPCExtender
commands:
    npcx:
        description: npc extender 
    civ:
        description: player town building commands